"use server";

import { revalidatePath } from "next/cache";

import { STAFF_ROLES } from "@/lib/domain/enums";
import { assignmentSchema, docId, reviewSubmissionSchema, submissionSchema } from "@/lib/domain/schemas";
import type { ActionResult, Assignment, Enrollment, Program, Submission } from "@/lib/domain/types";
import {
  REVIEWER_SUBMISSION_FLOW,
  STUDENT_SUBMISSION_FLOW,
  assertTransition,
  isAdmin,
} from "@/lib/domain/workflows";
import { assertBatchAccess } from "../access";
import { COL, col, countOf, fromSnap, queryDocs, serverNow, toTimestamp } from "../db";
import { adminDb } from "../firebase-admin";
import { notify, notifyProgramStudents } from "../notify";
import { UPLOAD_POLICIES, verifyUploadedFiles } from "../storage";
import { ActionError, actor, parse, run } from "./_utils";

function revalidateAssignments() {
  revalidatePath("/admin/assignments");
  revalidatePath("/admin/submissions");
  revalidatePath("/mentor", "layout");
  revalidatePath("/dashboard", "layout");
}

/* ------------------------- Staff: assignments ------------------------ */

/**
 * `assignmentId` is generated by the form up front so attachments can be uploaded
 * to `assignments/{assignmentId}/` before the first save.
 */
export async function saveAssignment(
  assignmentId: string,
  isNew: boolean,
  input: unknown,
): Promise<ActionResult<{ id: string }>> {
  return run(async () => {
    const session = await actor(STAFF_ROLES);
    const id = parse(docId, assignmentId);
    const data = parse(assignmentSchema, input);
    const ref = col(COL.assignments).doc(id);
    const existing = fromSnap<Assignment>(await ref.get());
    if (isNew && existing) throw new ActionError("Assignment already exists.");
    if (!isNew && !existing) throw new ActionError("Assignment not found.");

    const program = fromSnap<Program>(await col(COL.programs).doc(data.programId).get());
    if (!program) throw new ActionError("Program not found.");

    if (!isAdmin(session.role)) {
      if (!data.batchId) throw new ActionError("Mentors must target one of their batches.");
      if (existing?.batchId && existing.batchId !== data.batchId) {
        await assertBatchAccess(session, existing.batchId);
      }
    }
    if (data.batchId) {
      const batch = await assertBatchAccess(session, data.batchId);
      if (batch.programId !== program.id) throw new ActionError("That batch belongs to another program.");
    }

    const attachments = await verifyUploadedFiles(
      data.attachmentPaths,
      `internship-documents/assignments/${id}/`,
      UPLOAD_POLICIES.staffFile,
      existing?.attachments,
    );

    const payload = {
      programId: program.id,
      batchId: data.batchId || null,
      courseId: data.courseId || null,
      title: data.title,
      description: data.description,
      instructions: data.instructions,
      dueDate: toTimestamp(data.dueDate),
      maxScore: data.maxScore,
      allowFileUpload: data.allowFileUpload,
      attachments,
      status: data.status,
      updatedAt: serverNow(),
    };
    if (existing) await ref.update(payload);
    else
      await ref.set({
        ...payload,
        createdBy: session.uid,
        createdByName: session.name,
        createdAt: serverNow(),
      });

    if (data.status === "PUBLISHED" && existing?.status !== "PUBLISHED") {
      await notifyProgramStudents(program.id, data.batchId || null, {
        type: "NEW_ASSIGNMENT",
        title: "New assignment",
        body: `${data.title} — due ${new Date(data.dueDate).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}`,
        link: `/dashboard/assignments/${id}`,
      });
    }
    revalidateAssignments();
    return { id };
  }, "Assignment saved");
}

export async function deleteAssignment(assignmentId: string): Promise<ActionResult> {
  return run(async () => {
    const session = await actor(STAFF_ROLES);
    const id = parse(docId, assignmentId);
    const assignment = fromSnap<Assignment>(await col(COL.assignments).doc(id).get());
    if (!assignment) throw new ActionError("Assignment not found.");
    if (!isAdmin(session.role)) {
      if (!assignment.batchId) throw new ActionError("Only admins can delete program-wide assignments.");
      await assertBatchAccess(session, assignment.batchId);
    }
    if ((await countOf(col(COL.submissions).where("assignmentId", "==", id))) > 0) {
      throw new ActionError("Students have started this assignment. Unpublish it instead.");
    }
    await col(COL.assignments).doc(id).delete();
    revalidateAssignments();
  }, "Assignment deleted");
}

/* ------------------------- Student: submissions ---------------------- */

export async function saveSubmission(input: unknown): Promise<ActionResult<{ id: string }>> {
  return run(async () => {
    const session = await actor(["STUDENT"]);
    const data = parse(submissionSchema, input);
    const assignment = fromSnap<Assignment>(await col(COL.assignments).doc(data.assignmentId).get());
    if (!assignment || assignment.status !== "PUBLISHED") throw new ActionError("Assignment not found.");

    const enrollments = await queryDocs<Enrollment>(
      col(COL.enrollments).where("uid", "==", session.uid),
    );
    const enrollment = enrollments.find(
      (e) =>
        e.status === "ACTIVE" &&
        e.programId === assignment.programId &&
        (!assignment.batchId || assignment.batchId === e.batchId),
    );
    if (!enrollment) throw new ActionError("This assignment isn't part of your active enrollment.");
    if (!assignment.allowFileUpload && data.filePaths?.length) {
      throw new ActionError("File uploads are not enabled for this assignment.");
    }

    const id = `${assignment.id}_${session.uid}`;
    const ref = col(COL.submissions).doc(id);
    const saved = fromSnap<Submission>(await ref.get());
    const files = await verifyUploadedFiles(
      data.filePaths,
      `internship-documents/submissions/${id}/`,
      UPLOAD_POLICIES.submission,
      saved?.files,
    );
    const target = data.submit ? "SUBMITTED" : "IN_PROGRESS";

    await adminDb().runTransaction(async (tx) => {
      const current = fromSnap<Submission>(await tx.get(ref));
      assertTransition("submission", STUDENT_SUBMISSION_FLOW, current?.status ?? "NOT_STARTED", target);
      const payload = {
        assignmentId: assignment.id,
        assignmentTitle: assignment.title,
        uid: session.uid,
        studentName: enrollment.studentName,
        enrollmentId: enrollment.id,
        programId: assignment.programId,
        batchId: enrollment.batchId ?? null,
        status: target,
        githubUrl: data.githubUrl || null,
        liveUrl: data.liveUrl || null,
        explanation: data.explanation || null,
        files,
        maxScore: assignment.maxScore,
        updatedAt: serverNow(),
        ...(data.submit
          ? { submittedAt: serverNow(), late: new Date(assignment.dueDate).getTime() < Date.now() }
          : {}),
      };
      if (current) tx.update(ref, payload);
      else tx.set(ref, { ...payload, createdAt: serverNow() });
    });

    if (data.submit && enrollment.mentorId) {
      await notify([enrollment.mentorId], {
        type: "GENERAL",
        title: "New submission to review",
        body: `${enrollment.studentName} submitted “${assignment.title}”.`,
        link: `/mentor/submissions?open=${id}`,
      });
    }
    revalidateAssignments();
    return { id };
  }, (input as { submit?: unknown } | null)?.submit === true ? "Submitted for review!" : "Draft saved");
}

/* ------------------------- Staff: review ----------------------------- */

export async function reviewSubmission(input: unknown): Promise<ActionResult> {
  return run(async () => {
    const session = await actor(STAFF_ROLES);
    const data = parse(reviewSubmissionSchema, input);
    const ref = col(COL.submissions).doc(data.submissionId);
    const submission = fromSnap<Submission>(await ref.get());
    if (!submission) throw new ActionError("Submission not found.");
    if (!isAdmin(session.role)) {
      if (!submission.batchId) throw new ActionError("You are not assigned to this student.");
      await assertBatchAccess(session, submission.batchId);
    }
    if (typeof data.score === "number" && data.score > submission.maxScore) {
      throw new ActionError(`Score can't exceed ${submission.maxScore}.`);
    }
    if (data.status === "APPROVED" && typeof data.score !== "number") {
      throw new ActionError("Add a score to approve this submission.");
    }
    assertTransition("submission", REVIEWER_SUBMISSION_FLOW, submission.status, data.status);

    const batch = adminDb().batch();
    batch.update(ref, {
      status: data.status,
      ...(typeof data.score === "number" ? { score: data.score } : {}),
      ...(data.feedback ? { feedback: data.feedback } : {}),
      reviewedBy: session.uid,
      reviewedByName: session.name,
      reviewedAt: serverNow(),
      updatedAt: serverNow(),
    });
    if (typeof data.score === "number" && data.status !== "UNDER_REVIEW") {
      batch.set(col(COL.evaluations).doc(`sub_${submission.id}`), {
        uid: submission.uid,
        enrollmentId: submission.enrollmentId,
        type: "ASSIGNMENT",
        refId: submission.assignmentId,
        title: submission.assignmentTitle,
        score: data.score,
        maxScore: submission.maxScore,
        feedback: data.feedback || null,
        evaluatorId: session.uid,
        evaluatorName: session.name,
        createdAt: serverNow(),
      });
    }
    await batch.commit();

    if (data.status !== "UNDER_REVIEW") {
      await notify([submission.uid], {
        type: "ASSIGNMENT_FEEDBACK",
        title: data.status === "APPROVED" ? "Assignment approved ✅" : "Revision requested",
        body: `${submission.assignmentTitle}${typeof data.score === "number" ? ` — score ${data.score}/${submission.maxScore}` : ""}`,
        link: `/dashboard/assignments/${submission.assignmentId}`,
      });
    }
    revalidateAssignments();
  }, "Review saved");
}
